version: '3'
services:
  dbt-bq-dtc:
    build:
      context:  .
      target:   dbt-bigquery
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - ~/.dbt:/root/.dbt/
      - ~/google-cloud-sdk/dtc-de-377105-1c894de71cc1.json:/.google/credentials/google_credentials.json
    network_mode: host